name: Spring Boot & Gradle CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
          docker build -t ${{ secrets.IMAGE }} .
          docker tag ${{ secrets.IMAGE }} ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGE }}:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGE }}:${GITHUB_SHA::7}

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.EC2_PASS }}
          envs: GITHUB_SHA
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGE }}:${GITHUB_SHA::7}
            docker stop server
            docker run --env-file ./env.sh -d --rm --name server -p 8080:8080 ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGE }}:${GITHUB_SHA::7}
